In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("KarnalOriginal.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15964 entries, 0 to 15963
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   INDEX   15964 non-null  int64
 1   YEAR    15964 non-null  int64
 2   MN      15964 non-null  int64
 3   DT      15964 non-null  int64
 4   MAX     15262 non-null  float64
 5   MIN     14922 non-null  float64
 6   RF      13629 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 873.2 KB

In [4]:
df.sample(2)

      INDEX  YEAR  MN  DT   MAX   MIN   RF
1424  42137  1979   1   3  22.0   8.0  0.0
9281  42137  2007   4   6  35.8  14.8  0.0

In [5]:
all_dates = pd.date_range(
    start="1975-1-1",
    end="2025-12-31",
    freq='D'
)

In [6]:
df['YEAR'] = pd.to_datetime(
    df['YEAR'].astype(str) + '-' +
    df['MN'].astype(str) + '-' +
    df['DT'].astype(str)
)

In [7]:
df.sample(3)

       INDEX       YEAR  MN  DT   MAX   MIN   RF
12726  42137 2016-12-12  12  12  23.5  10.6  0.0
3383   42137 1984-06-17   6  17  38.0  28.5  0.0
3691   42137 1985-04-21   4  21  41.0  25.0  NaN

In [8]:
df = df.rename(columns={'YEAR': 'TIME'})

In [9]:
df=df.drop(["MN","DT","INDEX"],axis=1)

In [10]:
df = df.set_index('TIME')

df = df.reindex(all_dates)
df.index.name = 'TIME'

In [11]:
df =df.reset_index()

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18628 entries, 0 to 18627
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TIME    18628 non-null  datetime64[us]
 1   MAX     15262 non-null  float64
 2   MIN     14922 non-null  float64
 3   RF      13629 non-null  float64
dtypes: datetime64[us](1), float64(3)
memory usage: 582.3 KB

In [13]:
df.to_csv("Karnal.csv",index=False)